name: Deploy to dev

on:
  workflow_dispatch:
  pull_request:
    types: [closed]
    branches:
      - dev

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    environment: dev
    if: github.event.pull_request.merged == true

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy to Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            export PNPM_HOME="$HOME/.local/share/pnpm"
            export PATH="$PNPM_HOME:$PATH"
            export PATH="$HOME/.local/bin:$PATH"
            export PATH="$HOME/.npm-global/bin:$PATH"
            export PORT=${{ vars.PORT }}

            cd ${{ secrets.SSH_PATH }}
            git fetch --all
            git reset --hard origin/dev
            pnpm install --frozen-lockfile
            echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" > .env
            pnpm build
            pnpm start:pm2:dev
